<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.552">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Introduction to linear regression analysis - 6&nbsp; One Way ANOVA</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./06-Simulation.html" rel="next">
<link href="./04b-Continuous-Distributions.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.css">

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./05-One-Way-ANOVA.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">One Way ANOVA</span></a></li></ol></nav>
        <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Introduction to linear regression analysis</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">General Information</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./00-Recommended-Literature.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Recommended reading</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-Introduction-to-R.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction to R</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-Descriptive-Statistics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Descriptive Statistics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-Least-Squares.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Least Squares</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04a-Probability-Review.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Discrete Distributions (Review)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04b-Continuous-Distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Continuous Distributions (Review)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-One-Way-ANOVA.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">One Way ANOVA</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-Simulation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">A Simulation Study</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lecture_problems.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Задача от лекциите</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#the-data" id="toc-the-data" class="nav-link active" data-scroll-target="#the-data"><span class="header-section-number">6.1</span> The Data</a></li>
  <li><a href="#the-linear-regression-model-with-a-single-binary-predictor" id="toc-the-linear-regression-model-with-a-single-binary-predictor" class="nav-link" data-scroll-target="#the-linear-regression-model-with-a-single-binary-predictor"><span class="header-section-number">6.2</span> The Linear Regression Model with a single binary predictor</a></li>
  <li><a href="#mathematical-details-optional" id="toc-mathematical-details-optional" class="nav-link" data-scroll-target="#mathematical-details-optional"><span class="header-section-number">6.3</span> Mathematical Details (Optional)</a>
  <ul class="collapse">
  <li><a href="#the-ols-estimator-in-the-binary-predictor-case" id="toc-the-ols-estimator-in-the-binary-predictor-case" class="nav-link" data-scroll-target="#the-ols-estimator-in-the-binary-predictor-case"><span class="header-section-number">6.3.1</span> The OLS Estimator in the Binary Predictor Case</a></li>
  <li><a href="#what-about-the-standard-errors" id="toc-what-about-the-standard-errors" class="nav-link" data-scroll-target="#what-about-the-standard-errors"><span class="header-section-number">6.3.2</span> What about the standard errors?</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-simple-anova" class="quarto-section-identifier"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">One Way ANOVA</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="the-data" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="the-data"><span class="header-section-number">6.1</span> The Data</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Warning: to compile the notes you need the "bookdown" and the "broom" packages. Install them by</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="do">## running install.packages, see the commented lines below</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">require</span>(<span class="st">"tidyverse"</span>)) {</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">install.packages</span>(<span class="st">"tidyverse"</span>)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: tidyverse</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.0     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.1
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">require</span>(<span class="st">"broom"</span>)) {</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">install.packages</span>(<span class="st">"broom"</span>)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: broom</code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">require</span>(<span class="st">"patchwork"</span>)) {</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">install.packages</span>(<span class="st">"patchwork"</span>)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: patchwork</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in library(package, lib.loc = lib.loc, character.only = TRUE,
logical.return = TRUE, : there is no package called 'patchwork'</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># Downloading packages -------------------------------------------------------
- Downloading patchwork from CRAN ...           OK [3.1 Mb in 0.48s]
Successfully downloaded 1 package in 0.81 seconds.

The following package(s) will be installed:
- patchwork [1.2.0]
These packages will be installed into "~/work/econ2024/econ2024/renv/library/R-4.3/x86_64-pc-linux-gnu".

# Installing packages --------------------------------------------------------
- Installing patchwork ...                      OK [installed binary and cached in 1.0s]
Successfully installed 1 package in 1.1 seconds.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">require</span>(<span class="st">"latex2exp"</span>)) {</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">install.packages</span>(<span class="st">"latex2exp"</span>)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: latex2exp</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in library(package, lib.loc = lib.loc, character.only = TRUE,
logical.return = TRUE, : there is no package called 'latex2exp'</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># Downloading packages -------------------------------------------------------
- Downloading latex2exp from CRAN ...           OK [1.5 Mb in 0.81s]
Successfully downloaded 1 package in 0.95 seconds.

The following package(s) will be installed:
- latex2exp [0.9.6]
These packages will be installed into "~/work/econ2024/econ2024/renv/library/R-4.3/x86_64-pc-linux-gnu".

# Installing packages --------------------------------------------------------
- Installing latex2exp ...                      OK [installed binary and cached in 0.67s]
Successfully installed 1 package in 0.7 seconds.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(patchwork)</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>kids <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>  <span class="st">"https://raw.githubusercontent.com/feb-uni-sofia/econometrics2020-solutions/master/data/childiq.csv"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(kid_score, mom_hs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 434 Columns: 5
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
dbl (5): kid_score, mom_hs, mom_iq, mom_work, mom_age

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>kids <span class="sc">%&gt;%</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>() <span class="sc">%&gt;%</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div id="tbl-kids-head" class="cell quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-kids-head-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6.1: First few rows of the data set <code>kids</code>.
</figcaption>
<div aria-describedby="tbl-kids-head-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">kid_score</th>
<th style="text-align: right;">mom_hs</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">65</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: right;">98</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="odd">
<td style="text-align: right;">85</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: right;">83</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="odd">
<td style="text-align: right;">115</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: right;">98</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Variables description:</p>
<ul>
<li><code>kid_score</code>: (numeric) Kid’s IQ score.</li>
<li><code>mom_hs</code> (numeric): This variable has only two possible values (a binary variable): 1 if the mother of the child has finished high school, and 0 otherwise.</li>
</ul>
<p>For the sake of simplicity we will assume that the children in the sample (in the data set <code>kids</code>) were selected at random from all children living in the US at the time of the survey.</p>
<p>Research question: Do children whose mother did not finish a high school (<code>mom_hs = 0</code>) tend to achieve lower IQ scores compared to the children of mothers with a high school degree (<code>mom_hs = 1</code>).</p>
</section>
<section id="the-linear-regression-model-with-a-single-binary-predictor" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="the-linear-regression-model-with-a-single-binary-predictor"><span class="header-section-number">6.2</span> The Linear Regression Model with a single binary predictor</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Where to get the data</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>kids <span class="sc">%&gt;%</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>      <span class="do">## Map the status of the mother to the y-axis.</span></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>      <span class="do">## The factor function converts mom_hs to a factor variable</span></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>      <span class="do">## so that ggplot would not treat mom_hs as a continuous variable.</span></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>      <span class="at">y =</span> <span class="fu">factor</span>(mom_hs),</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>      <span class="do">## Map the kid_score column to the x-axis.</span></span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>      <span class="at">x =</span> kid_score</span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(</span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a>    <span class="do">## Add some noise to each observation so that we can </span></span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a>    <span class="do">## see the collection of dots. Without this noise</span></span>
<span id="cb17-16"><a href="#cb17-16" aria-hidden="true" tabindex="-1"></a>    <span class="do">## all dots would lie on two straight lines</span></span>
<span id="cb17-17"><a href="#cb17-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">position =</span> <span class="st">"jitter"</span></span>
<span id="cb17-18"><a href="#cb17-18" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb17-19"><a href="#cb17-19" aria-hidden="true" tabindex="-1"></a>  <span class="do">## Draws the two boxplots to help us see the centers and the spreads</span></span>
<span id="cb17-20"><a href="#cb17-20" aria-hidden="true" tabindex="-1"></a>  <span class="do">## of the distributions of the scores in the two groups</span></span>
<span id="cb17-21"><a href="#cb17-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(</span>
<span id="cb17-22"><a href="#cb17-22" aria-hidden="true" tabindex="-1"></a>    <span class="do">## Makes the boxplots transparent so that we can see the dots</span></span>
<span id="cb17-23"><a href="#cb17-23" aria-hidden="true" tabindex="-1"></a>    <span class="do">## behind them</span></span>
<span id="cb17-24"><a href="#cb17-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">alpha =</span> <span class="fl">0.5</span></span>
<span id="cb17-25"><a href="#cb17-25" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb17-26"><a href="#cb17-26" aria-hidden="true" tabindex="-1"></a>  <span class="do">## Sets human-readable labels for the two axes</span></span>
<span id="cb17-27"><a href="#cb17-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb17-28"><a href="#cb17-28" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"IQ score"</span>,</span>
<span id="cb17-29"><a href="#cb17-29" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Status of the kid's mother"</span></span>
<span id="cb17-30"><a href="#cb17-30" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-kid-score-plot" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-kid-score-plot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="05-One-Way-ANOVA_files/figure-html/fig-kid-score-plot-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-kid-score-plot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.1: IQ scores of the children by the status of their mother (high school degree/no high school degree). The plot adds a small amount of noise to the observations to avoid overplotting.
</figcaption>
</figure>
</div>
</div>
</div>
<div id="exr-summary-kids" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 6.1</strong></span> Use the following code stub to compute the average IQ scores for the two groups of children in the <code>kids</code> data set.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute the average IQ scores for the two groups</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Uncomment the following code and fill in the ellipsis</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a><span class="co"># kids %&gt;%</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a><span class="co">#   group_by(...) %&gt;%</span></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a><span class="co">#   summarize(</span></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a><span class="co">#     ... = mean(...)</span></span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a><span class="co">#   )</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<p>Let us see how we can model the average IQ scores within a simple linear model.</p>
<p><span class="math display">
\begin{align*}
&amp; i = 1,\ldots, n = 434 \text{ observations}\\
&amp; y_i: \text{IQ score} \\
&amp; \hat{y}_i: \text{Predicted IQ score} \\
&amp; x_i \in \{0, 1\}: \text{status of the mother}
\end{align*}
</span></p>
<p>The linear model is then</p>
<p><span class="math display">
y_i = \beta_0 + \beta_1 x_i + e_i, e_i \sim N(0, \sigma^2)
</span></p>
<p>The predicted IQ score for the <span class="math inline">i</span>-th child is</p>
<p><span class="math display">
\hat{y} = \hat{\beta}_0 + \hat{\beta}_1 x
</span></p>
<p>Alternatively (and more generally) we can write the model as:</p>
<p><span id="eq-simple-anova"><span class="math display">
\begin{align*}
&amp; y_i \sim N(\mu_i, \sigma^2), \quad i = 1,\ldots,n \\
&amp; \mu_i = \beta_0 + \beta_1 x_i, \quad x_i \in \{0, 1\}
\end{align*}
\tag{6.1}</span></span></p>
<p>Let us see what the model coefficients mean. This becomes obvious when we consider the expected value of <span class="math inline">y</span> (the IQ score) for the two possible values of <span class="math inline">x</span>. For <span class="math inline">x = 1</span> (children with a mother with a HS degree) the expected IQ score is:</p>
<p><span id="eq-mu-x-1"><span class="math display">
\mu_1 = \beta_0 + \beta_1 \cdot 1
\tag{6.2}</span></span></p>
<p>For <span class="math inline">x = 0</span> (children with a mother without a HS degree)</p>
<p><span id="eq-mu-x-0"><span class="math display">
\mu_0 = \beta_0 + \beta_1 \cdot 0
\tag{6.3}</span></span></p>
<p>If you take the difference between equations <a href="#eq-mu-x-1" class="quarto-xref"><span>6.2</span></a> and <a href="#eq-mu-x-0" class="quarto-xref"><span>6.3</span></a> you will get:</p>
<p><span class="math display">
\begin{align*}
\beta_0 &amp; = \mu_0 \\
\beta_1 &amp; = \mu_1 - \mu_0
\end{align*}
</span></p>
<p>Therefore, the constant in the model (<span class="math inline">\beta_0</span>) equals the population average IQ score of children in the <span class="math inline">x = 0</span> group. The slope coefficient <span class="math inline">\beta_1</span> equals the difference between the population average IQ scores. <a href="#fig-simple-anova-model-vis" class="quarto-xref">Figure&nbsp;<span>6.2</span></a> visualizes the population of children (as the model in <a href="#eq-simple-anova" class="quarto-xref">Equation&nbsp;<span>6.1</span></a> sees it). There are two groups of children in that population. The first has an average IQ score of <span class="math inline">\mu_0</span>, the second group has an average IQ score of <span class="math inline">\mu_1</span>. The children in both groups are normally distributed and the two distributions have the same standard deviation (spread).</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Scale for x is already present.
Adding another scale for x, which will replace the existing scale.</code></pre>
</div>
<div class="cell-output-display">
<div id="fig-simple-anova-model-vis" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-simple-anova-model-vis-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="05-One-Way-ANOVA_files/figure-html/fig-simple-anova-model-vis-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-simple-anova-model-vis-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.2: Distribution of IQ scores in the population of children according to <a href="#eq-simple-anova" class="quarto-xref">Equation&nbsp;<span>6.1</span></a>.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Within that model our research question boils down to examining <span class="math inline">\beta_1</span> (the difference between the population averages). If <span class="math inline">\beta_1</span> is positive, then children born to a mother with a HS degree would tend to perform better at the IQ test.</p>
<p>The first obstacle to answering the research question is that we don’t know the value of <span class="math inline">\beta_1</span>. Therefore, we rely on the sample to learn something about its value.</p>
<p>In the previous section we discussed the OLS estimator and now we will use it to find the best (in terms of lowest RSS) estimates for <span class="math inline">\beta_0</span> and <span class="math inline">\beta_1</span>. As in the previous section will will find these using the <code>lm</code> function. We will also store the result of <code>lm</code> in an object so that we can use it later without running <code>lm</code> every time.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Run lm and save the output in an object called "fit"</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">lm</span>(kid_score <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> mom_hs, <span class="at">data =</span> kids)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="do">## Print the object storing the lm output</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>fit</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = kid_score ~ 1 + mom_hs, data = kids)

Coefficients:
(Intercept)       mom_hs  
      77.55        11.77  </code></pre>
</div>
</div>
<p>Look at the output of <code>lm</code> and write down the estimated regression equation:</p>
<p><span class="math display">
\begin{align*}
\hat{\mu} = 77.55 + 11.77 x
\end{align*}
</span></p>
<p>This equation summarizes the <em>sample</em>. The children that we have selected and actually observed. For these children there was a difference of average IQ scores of 11.77. However, the sample only includes 434 children. A more interesting question is whether there is a difference between the average IQ scores between the two groups (mother with HS degree, mother without HS degree) in the <em>population</em> from which the sample was selected.</p>
<p>An interesting research hypothesis that we can test is whether the <em>population</em> coefficient <span class="math inline">\beta_1</span> is equal to zero, for example against a two-sided alternative <span class="math inline">\beta_1 \neq 0</span>.</p>
<p><span class="math display">
H_0: \beta_1 = 0 \\
H_1: \beta_1 \neq 0
</span></p>
<p>A test of this hypothesis against the alternative is a t-test with a test statistic</p>
<p><span class="math display">
\text{t-statistic} = \frac{\hat{\beta}_1 - 0}{se(\hat{\beta}_1)}
</span></p>
<p>If <span class="math inline">\beta_1</span> is really equal to zero, then this statistic follows a t-distribution with <span class="math inline">n - p</span> degrees of freedom. The critical values of this test at <span class="math inline">\alpha = 0.05</span> probability of wrong rejection of the null hypothesis.</p>
<p>For the <code>kids</code> data set you can test this hypothesis using the output of <code>summary</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = kid_score ~ 1 + mom_hs, data = kids)

Residuals:
   Min     1Q Median     3Q    Max 
-57.55 -13.32   2.68  14.68  58.45 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   77.548      2.059  37.670  &lt; 2e-16 ***
mom_hs        11.771      2.322   5.069 5.96e-07 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 19.85 on 432 degrees of freedom
Multiple R-squared:  0.05613,   Adjusted R-squared:  0.05394 
F-statistic: 25.69 on 1 and 432 DF,  p-value: 5.957e-07</code></pre>
</div>
</div>
<p>The second row in the coefficients table corresponds to our <span class="math inline">\hat{\beta}_1</span> in our model notation (the coefficient of <code>mom_hs</code>). You can find the estimated standard error of <span class="math inline">\hat{\beta}_1</span> in the second column (<code>Std. Error</code>).</p>
<p><span class="math display">
\text{t-statistic}^{obs} = \frac{11.77 - 0}{2.322} = 5.0689
</span></p>
<p>You can find this value in the column <code>t value</code> in the <code>summary</code> above. This t-statistic is shown in the regression output by almost all statistical software, because the hypothesis</p>
<p><span class="math display">
H_0: \beta_1 = 0 \\
H_1: \beta_1 \neq 0
</span></p>
<p>is particularly interesting. If true it implies that there are no population-level differences between the average IQ scores of the two groups of children.</p>
<p>In order to make a decision whether to reject this hypothesis or not, we compare the observed t-statistic to two critical values (because the alternative is two-sided).</p>
<p>The critical values at a five percent error probability (wrong rejection of a true null hypothesis) are derived from the t-distribution. You can find a detailed explanation in <a href="06-Simulation.html" class="quarto-xref"><span>Chapter 7</span></a>.</p>
<p>The quantiles of the t-distribution are</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>alpha <span class="ot">&lt;-</span> <span class="fl">0.05</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fu">qt</span>(alpha <span class="sc">/</span> <span class="dv">2</span>, <span class="at">df =</span> <span class="fu">nrow</span>(kids) <span class="sc">-</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -1.965471</code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qt</span>(<span class="dv">1</span> <span class="sc">-</span> alpha <span class="sc">/</span> <span class="dv">2</span>, <span class="at">df =</span> <span class="fu">nrow</span>(kids) <span class="sc">-</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.965471</code></pre>
</div>
</div>
<p>The observed t-statistic equals 5.0689 and is therefore greater than the upper critical value (1.96). Therefore we reject the null hypothesis at a significance level <span class="math inline">1 - \alpha = 0.95</span> (this is another way to state the probability of wrong rejection of a true null hypothesis).</p>
<p>Apart from the point estimate for the difference of average IQ scores (11.77 points) we usually also want to communicate the uncertainty of this estimate. One description of that uncertainty is the (estimated) standard error of the estimator for the regression coefficient.</p>
<p>One way to construct a confidence interval for the coefficients is to invert the two-sided t-test (see <a href="06-Simulation.html#sec-sim-ci" class="quarto-xref"><span>Section 7.7</span></a> for more details).</p>
<p>We will use the critical values of the t-test at the 95 percent significance level to obtain an confidence interval (CI) with a 95 percent coverage probability:</p>
<p><span id="eq-ci-kids-beta1"><span class="math display">
P\left(\hat{\beta}_1 - 1.96 se(\hat{\beta}_1)  &lt; \beta_1 &lt; \hat{\beta}_1 + 1.96 se(\hat{\beta}_1) \right) = 0.95
\tag{6.4}</span></span></p>
<p>Notice that the boundaries of the interval are random variables (because <span class="math inline">\hat{\beta}_1</span> and <span class="math inline">se(\hat{\beta}_1)</span>) are random variables (they depend on the data). For the sample of children in <code>kids</code> we obtain <em>estimates</em> for these boundaries: <span class="math inline">[11.77 - 1.96 \cdot 2.322; 11.77 + 1.96 \cdot 2.322] \approx [7.2; 16.3]</span>. Based on these estimated boundaries we would say that range of plausible values for the difference between the population IQ score averages between 7.2 and 16.3.</p>
<p>Notice that in interpreting the boundaries of the CI we don’t say that the probability of <span class="math inline">\beta_1</span> being between 7.2 and 16.3 is 0.95. Generally this statement does not make any sense, because we have assumed that <span class="math inline">\beta_1</span> is a fixed number (not random). The probability statement in <a href="#eq-ci-kids-beta1" class="quarto-xref">Equation&nbsp;<span>6.4</span></a> does make sense, because the boundaries are random variables (depend on the data), but the statement <span class="math inline">P(7.2 &lt; \beta_1 &lt; 16.3) = 0.95</span> does not!</p>
</section>
<section id="mathematical-details-optional" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="mathematical-details-optional"><span class="header-section-number">6.3</span> Mathematical Details (Optional)</h2>
<section id="the-ols-estimator-in-the-binary-predictor-case" class="level3" data-number="6.3.1">
<h3 data-number="6.3.1" class="anchored" data-anchor-id="the-ols-estimator-in-the-binary-predictor-case"><span class="header-section-number">6.3.1</span> The OLS Estimator in the Binary Predictor Case</h3>
<p>In the case when <span class="math inline">x_i \in \{0, 1\}</span> the average of <span class="math inline">x</span>, i.e <span class="math inline">\overline{x}</span> is simply the proportion of ones, lets say <span class="math inline">n_1 / n</span>. Notice that the average of the squared <span class="math inline">x</span> is the same as the average of <span class="math inline">x</span>, because <span class="math inline">x</span> only contains zeroes and ones (therefore <span class="math inline">x_i^2 = x_i</span>). The average of the product of <span class="math inline">x</span> and <span class="math inline">y</span> is equal to the sum of <span class="math inline">y</span> where the <span class="math inline">x = 1</span>, because the other values in <span class="math inline">y</span> are multiplied by zero.</p>
<p><span class="math display">
\begin{align*}
\overline{x^2} = &amp; \frac{1}{n}\sum_{i = 1}^{n} x_i^2 =  \\
               = &amp; \frac{1}{n} \sum_{i = 1}^n x_i \\
               = &amp; \bar{x}
\end{align*}
</span></p>
<p><span class="math display">
\begin{align*}
\overline{xy} = &amp; \frac{1}{n} \sum_{i = 1}^{n} x_i y_i = \\
              = &amp; \frac{1}{n}\left(\sum_{i: x_i = 0} y_i \cdot 0 + \sum_{ i: x_i = 1} y_i \cdot 1 \right) \\
              = &amp; \frac{1}{n}\sum_{i: x_i = 1} y_i \\
              = &amp; \frac{n_1}{n_1}\frac{1}{n} \sum_{i: x_i = 1} y_i \\
              = &amp; \frac{n_1}{n} \bar{y}_{1}
\end{align*}
</span></p>
<p>In the last expression we use <span class="math inline">\bar{y}_1</span> to denote the sample average of the <span class="math inline">x = 1</span> group.</p>
<p>Therefore the expression for <span class="math inline">\hat{\beta}_1</span> simplifies to:</p>
<p><span class="math display">
\hat{\beta}_1 = \frac{ \frac{n_1}{n} \overline{y}_{1} - \overline{x}\overline{y}}{\overline{x} - \overline{x}^2} \\
\hat{\beta}_1 = \frac{\overline{y}_{1} - \overline{y}}{1 - \frac{n_1}{n}} \\
\hat{\beta}_1 = \frac{\overline{y}_{1} - \overline{y}}{\frac{n - n_1}{n}} \\
\hat{\beta}_1 = \frac{\overline{y}_{1} - \overline{y}}{\frac{n_0}{n}} \\
</span></p>
<p>Furthermore, the average of <span class="math inline">y</span> is simply the weighted average of the two group means. Let there be <span class="math inline">n_0</span> observations with <span class="math inline">x_i = 0</span> and <span class="math inline">n_1</span> observations with <span class="math inline">x_i = 1</span>.</p>
<p><span class="math display">
\overline{y} = \frac{1}{n}\left(\sum_{x_i = 0} y_i + \sum_{x_i = 0} y_i\right) \\
\overline{y} = \frac{1}{n}\left(n_0 \overline{y}_0 + n_1 \overline{y}_1 \right)
</span></p>
<p>Substituting gives us:</p>
<p><span class="math display">
\hat{\beta}_1 = \frac{\overline{y}_{1} - \frac{1}{n}\left(n_0 \overline{y}_0 + n_1 \overline{y}_1 \right)}{\frac{n_0}{n}} \\
</span></p>
<p>When you simplify the above expression (this is left as an exercise) you will arrive at:</p>
<p><span class="math display">
\hat{\beta}_1 = \bar{y}_1 - \bar{y}_0
</span></p>
<p>From the equation for <span class="math inline">\hat{\beta}_0</span> we get:</p>
<p><span class="math display">
\hat{\beta}_0 = \bar{y} - (\bar{y}_1 - \bar{y}_0) \bar{x}
</span></p>
<p>Taking into account that <span class="math inline">\bar{x} = n_1 / n</span> this equation simplifies to</p>
<p><span class="math display">
\hat{\beta}_0 = \overline{y}_0
</span></p>
</section>
<section id="what-about-the-standard-errors" class="level3" data-number="6.3.2">
<h3 data-number="6.3.2" class="anchored" data-anchor-id="what-about-the-standard-errors"><span class="header-section-number">6.3.2</span> What about the standard errors?</h3>
<p>In the case of the simple ANOVA model the standard errors of both coefficients are pretty easy to derive, because the estimators are simply a group average (<span class="math inline">\hat{\beta}_0</span>) and the difference between two group averages (<span class="math inline">\hat{\beta}_1</span>).</p>
<p>We can compute the variance of <span class="math inline">\hat{beta}_0</span>. Note that when studying the statistical properties of an estimator like the OLS estimator for <span class="math inline">\beta_0</span> we treat the data <span class="math inline">y_i</span> as random variables. In the following derivation we assume that the <span class="math inline">y_i</span> are not correlated.</p>
<p><span id="eq-simple-anova-var-beta0"><span class="math display">
\begin{align*}
Var(\hat{\beta}_0) &amp; = Var\left(\frac{1}{n_0}\sum_{i: x_i = 0} y_i \right) \\
                   &amp; = \frac{1}{n_0^2} \sum_{i: x_i = 0} Var(y_i) \\
                   &amp; = \frac{1}{n_0^2} \sum_{i: x_i = 0} \sigma^2 \\
                   &amp; = \frac{n_0 \sigma^2}{n_0^2} \\
                   &amp; = \frac{\sigma^2}{n_0}
\end{align*}
\tag{6.5}</span></span></p>
<p>For the variance of <span class="math inline">\hat{beta}_1</span> we obtain. In the derivation we use the assumption of <span class="math inline">y_i</span> being uncorrelated and the fact that the variance of a difference of uncorrelated random variables equals the sum of their variances.</p>
<p><span id="eq-simple-anova-var-beta1"><span class="math display">
\begin{align*}
Var(\hat{\beta}_1) &amp; = Var\left(\frac{1}{n_1}\sum_{i: x_i = 1} y_i - \frac{1}{n_0}\sum_{i: x_i = 0} y_i\right) \\
                   &amp; = Var\left(\frac{1}{n_1}\sum_{i: x_i = 1} y_i \right) + Var\left(\frac{1}{n_0}\sum_{i: x_i = 0} y_i\right) \\
                   &amp; = \frac{\sigma^2}{n_1} + \frac{\sigma^2}{n_0} \\
                   &amp; = \sigma^2 \left(\frac{1}{n_0} + \frac{1}{n_1}\right)
\end{align*}
\tag{6.6}</span></span></p>
<p>The variances of the two coefficients involve the unknown parameter <span class="math inline">\sigma^2</span>. From the expressions for the variances you will notice that the variances increase in <span class="math inline">\sigma^2</span>. This should make sense intuitively. <span class="math inline">\sigma^2</span> describes how much noise the data contains (random deviations from the regression line). Estimating the coefficients from noisy data will result in uncertain estimates (high variances).</p>
<p>In order to arrive to estimates the coefficient variances we need a way to estimate <span class="math inline">\sigma^2</span> from the data. Here we will take a theorem from mathematical statistics that says that</p>
<p><span id="eq-sigma-estimator"><span class="math display">
\hat{\sigma}^2 = \frac{1}{n - p} \text{RSS}
\tag{6.7}</span></span></p>
<p>is an unbiased estimator for <span class="math inline">\sigma</span>. In the above expression <span class="math inline">n</span> is the number of observations and <span class="math inline">p</span> is the number of coefficients in the model. RSS is the residual sum of squares <span class="quarto-unresolved-ref">?sec-ols-intro</span>.</p>
<p><span class="math display">
E\hat{\sigma}^2 = \sigma
</span></p>
<p>Plugging in this estimator for <span class="math inline">\sigma^2</span> into <a href="#eq-simple-anova-var-beta0" class="quarto-xref">Equation&nbsp;<span>6.5</span></a> and <a href="#eq-simple-anova-var-beta1" class="quarto-xref">Equation&nbsp;<span>6.6</span></a> yields the following estimators for the variances of the model coefficients.</p>
<p><span class="math display">
\begin{align*}
Var(\hat{\beta}_0) = &amp; \frac{\hat{\sigma}^2}{n_0} \\
Var(\hat{\beta}_1) = &amp; \hat{\sigma}^2 \left(\frac{1}{n_0} + \frac{1}{n_1}\right)
\end{align*}
</span> Let us compare the two formulas with the standard errors from the <code>lm</code> output (printed here again for convinience).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = kid_score ~ 1 + mom_hs, data = kids)

Residuals:
   Min     1Q Median     3Q    Max 
-57.55 -13.32   2.68  14.68  58.45 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   77.548      2.059  37.670  &lt; 2e-16 ***
mom_hs        11.771      2.322   5.069 5.96e-07 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 19.85 on 432 degrees of freedom
Multiple R-squared:  0.05613,   Adjusted R-squared:  0.05394 
F-statistic: 25.69 on 1 and 432 DF,  p-value: 5.957e-07</code></pre>
</div>
</div>
<p>The number of children in the two groups are <span class="math inline">n_0 = 93</span> and <span class="math inline">n_1 = 341</span>. The number of observations is <span class="math inline">n = n_0 + n_1 = 434</span>. The number of coefficients in the model is <span class="math inline">p = 2</span>. We can compute the RSS by extracting the residuals from the model fit object (for example by using the <code>residuals</code> function).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>res <span class="ot">&lt;-</span> <span class="fu">residuals</span>(fit)</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(res <span class="sc">^</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 170261.2</code></pre>
</div>
</div>
<p>The estimate for <span class="math inline">\sigma^2</span> is therefore:</p>
<p><span class="math display">
\hat{\sigma}^2 = \frac{170261.2}{434 - 2} = 394.1231 \\
\hat{\sigma} = \sqrt{\hat{\sigma}^2} = 19.85
</span></p>
<p>You can find last value under <em>residual standard error</em> in the summary of the <code>lm</code> output above.</p>
<p>Now let us compute the estimated variances and standard deviations of the coefficients:</p>
<p><span class="math display">
\begin{align*}
Var(\hat{\beta}_0) &amp; = \frac{\hat{\sigma}^2}{n_0} = \frac{394.1}{93} = 4.23 \\
se(\hat{\beta}_0) &amp; = \sqrt{Var(\hat{\beta}_0)} = \sqrt{4.23} = 2.059 \\
Var(\hat{\beta}_1) &amp; = \hat{\sigma}^2 \left(\frac{1}{n_0} + \frac{1}{n_1}\right)  = 394.1 \left(\frac{1}{93} + \frac{1}{341}\right) = 5.39\\
se(\hat{\beta}_1) &amp; = \sqrt{Var(\hat{\beta}_1)} = \sqrt{5.39} = 2.32
\end{align*}
</span></p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./04b-Continuous-Distributions.html" class="pagination-link" aria-label="Continuous Distributions (Review)">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Continuous Distributions (Review)</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./06-Simulation.html" class="pagination-link" aria-label="A Simulation Study">
        <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">A Simulation Study</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>