project:
  type: book

book:
  title: "Introduction to linear regression analysis"
  author: "Boyko Amarov"
  date: "4/11/2023"
  chapters:
    - index.qmd
    - 00-Recommended-Literature.qmd
    - 01-Introduction-to-R.qmd
    - 02-Descriptive-Statistics.qmd
    - 03-Probability-Review.qmd
    - 04-Least-Squares.qmd          
    # - 00-Homework-Instructions.qmd  
    # - 02a-Continuous-Distributions.qmd
    # - 03-Simple-Linear-Model.qmd
    # - 04-Simple-ANOVA.qmd
    # - 05-Hypothesis-Testing-and-CI.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    html-math-method: katex

editor: visual
